### ISSUE TITLE
Red "error" tile not going away.

### ISSUE THREAD

**Issue by humblecoder** [davidgaroro/vuetify-swipeout#1]
When I swipe to remove an item, the main tile goes away, however, the red "background" doesn't disappear thereby obscuring the next item in the list.  Going to take a look at the source now, but would you mind explicitly specifying the mechanism by which that occurs?

**Comment by davidgaroro** [comment]
Hey @humblecoder ! 😄 

Can you provide me with more information? What browser are you using?

**Comment by humblecoder** [comment]
Apologies @davidgaroro.  It was a class naming issue.  I should have closed this days ago.
